name: 中青日常

on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 1-15 * * *'
  watch:
    types: started

env:
  TZ: Asia/Shanghai    # 事实证明这个无用

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
        YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
        YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
    steps:
      - name: Checkout   
        run: |
          git clone https://github.com/nekomiao123/youth_read_helper.git ~/youth_read_helper 
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YOUTH_HEADER
        run: |
          cd ~/youth_read_helper
          npm install
      - name: '运行 【中青看点】'
        if: env.YOUTH_HEADER
        run: |
          cd ~/youth_read_helper
          node Task/youth.js
        env:
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY}}
          BARK_PUSH: ${{ secrets.BARK_PUSH}}
          BARK_SOUND: ${{ secrets.BARK_SOUND}}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
          TG_USER_ID: ${{ secrets.TG_USER_ID}}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN}}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET}}
          QYWX_KEY: ${{ secrets.QYWX_KEY}}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY}}
          QQ_SKEY: ${{ secrets.QQ_SKEY}}
          QQ_MODE: ${{ secrets.QQ_MODE}}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
          TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST}}
          TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT}}
